name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    env:
      SECRET_CODE: ${{ secrets.SECRET_CODE }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      EXPIRY: ${{ secrets.EXPIRY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
